from django.db import models

from transaction.models import Transaction


# from beam.btc_payment.models import coinbase


class GoCoinInvoice(models.Model):

    UNPAID = 'UNPD'
    PAID = 'PAID'
    UNDERPAID = 'UNDP'
    READY_TO_SHIP = 'SHIP'
    INVALID = 'INVD'
    MERCHANT_REVIEW = 'MRCH'

    INVOICE_STATES = (
        (UNPAID, 'unpaid'),
        (PAID, 'paid'),
        (UNDERPAID, 'underpaid'),
        (READY_TO_SHIP, 'ready to ship'),
        (INVALID, 'invalid'),
        (MERCHANT_REVIEW, 'manual handling required')
    )

    transaction = models.OneToOneField(
        Transaction,
        related_name='gocoin_invoice',
        help_text='Transaction associated with this payment'
    )

    invoice_id = models.CharField(
        'Invoice ID',
        max_length=36,
        help_text='UUID identifying generated invoice'
    )

    btc_address = models.CharField(
        'BTC Wallet Address',
        max_length=34,
        help_text='Wallet generated to receive this payment'
    )

    btc_usd = models.FloatField(
        'BTC to USD Exchange Rate',
        null=True,
        help_text='exchange rate from BTC to USD applied for this payment'
    )

    sender_usd = models.FloatField(
        'Sender Currency to USD Exchange Rate',
        null=True,
        help_text='exchange rate from sender currency to USD applied for this payment'
    )

    state = models.CharField(
        'State',
        max_length=4,
        choices=INVOICE_STATES,
        default=UNPAID,
        help_text='State of the Coinbase Invoice'
    )


# class Coinbase_Payment(models.Model):

#     transaction = models.OneToOneField(
#         Transaction,
#         related_name='coinbase_payment',
#         help_text='Transaction associated with this payment'
#     )

#     coinbase_button_code = models.CharField(
#         'Coinbase Button Code',
#         blank=True,
#         max_length=50,
#         help_text='Represents button generated by Coinbase to receive payment.'
#     )

#     coinbase_order_reference = models.CharField(
#         'Coinbase Order Reference',
#         blank=True,
#         max_length=10,
#         help_text='Reference Code used to indentify Coinbase Order related to this transaction. Stored for tracking purposes.'
#     )

#     def generate_coinbase_button(self):
#         self.coinbase_button_code = coinbase.generate_button(
#             price=self.amount_gbp,
#             reference_number=self.reference_number,
#             transaction_id=self.id
#         )
#         self.save()
