
PRICING_EXPIRED = '0'
PROFILE_INCOMPLETE = '1'
ADDITIONAL_DOCUMENTS_MISSING = '2'
DOCUMENTS_NOT_VERIFIED = '3'
TRANSACTION_LIMIT_EXCEEDED = '4'
COUNTRY_NOT_SUPPORTED = '5'
SENDING_CURRENCY_NOT_SUPPORTED = '6'
